// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKEUs1Xu9p_zfmEBnKqQE4nwI0dwqC2wI',
    appId: '1:964053587416:web:aaceadd92df40dc0324ead',
    messagingSenderId: '964053587416',
    projectId: 'pretike-442f7',
    authDomain: 'pretike-442f7.firebaseapp.com',
    storageBucket: 'pretike-442f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ0g4zUR4Hs78mNuaLMRwYt93wEslae5A',
    appId: '1:964053587416:android:75f7827d0147a0d0324ead',
    messagingSenderId: '964053587416',
    projectId: 'pretike-442f7',
    storageBucket: 'pretike-442f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC58jR768hAV-Jehad8aVqgzKyXy4Gt6B4',
    appId: '1:964053587416:ios:3b09156aa36ba2c0324ead',
    messagingSenderId: '964053587416',
    projectId: 'pretike-442f7',
    storageBucket: 'pretike-442f7.appspot.com',
    iosClientId: '964053587416-dvatjrg01i9ve62ct34vsdjp3eta3t7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.pretike',
  );
}
